### ISSUE TITLE
crash on onPostExecute 

### ISSUE THREAD

**Issue by jbyu** [Everyplay/everyplay-android-sdk#10]
Fatal Exception: java.lang.NullPointerException
com.everyplay.Everyplay.communication.b.d.onPostExecute (Unknown Source)
android.os.AsyncTask.finish (AsyncTask.java:632)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by paugit** [comment]
Unable to reproduce. If this issue is still valid, please provide more information and re-open the issue.
