### ISSUE TITLE
Can not build with version 1.5.6

### ISSUE THREAD

**Issue by hoang89yenthe** [Everyplay/everyplay-android-sdk#15]
I can not build with lastest version 1.5.6
This is my mess: 
Error:Execution failed for task ':everyplay-android:ndkBuild'.
> Process 'command 'C:\AndroidSDK\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2
Please help.

**Comment by rebbTRSi** [comment]
Everyplay now updated and should fix your problem. Everyplay now updated and should fix your problem.
