### ISSUE TITLE
When can android use FaceCam to record microphone？

### ISSUE THREAD

**Issue by woniu0936** [Everyplay/everyplay-android-sdk#16]
Looking forward to your reply，thanks！

**Comment by Karmazz** [comment]
Hi there,

this is possible with the current version of the SDK.

Please test watching the replay through Everyplay's built-in video player. Our website is currently experiencing an issue which prevents the FaceCam track from playing on some web browsers.

**Comment by woniu0936** [comment]
sorry for the late reply，Whether to support custom recording output directory？Forgive me for my poor English

**Comment by paugit** [comment]
Unfortunately there is no API for custom output directory.
