### ISSUE TITLE
[Enhancement] Deploy .aar library to public repository

### ISSUE THREAD

**Issue by obigu** [Everyplay/everyplay-android-sdk#7]
It would be extremely useful have the .aar libray files accessible from a public repository to be able to easily add the dependency in the Android project build.gradle configuration file. 

It is currently very simple to add Everyplay Android SDK library from Eclipse but, now that is not supported anymore, setting it up in Android Studio via Gradle is much more complex. Now that the project is gradleized, I think it would make sense to make it available from a public repo.

**Comment by aet** [comment]
there's a few things we're not entirely happy with Gradle yet (it's a work in progress, at least they finally got Android Studio out in some form :), but we'll try to get it included on future releases, thanks
